import type { Trip } from "./types"

export const mockTrips: Trip[] = [
  {
    id: "trip-osaka",
    title: "오사카 먹킷리스트 여행",
    destination: "오사카",
    country: "일본",
    startDate: "2025-10-24",
    endDate: "2025-10-27",
    coverColor: "var(--chart-1)",
    budgetKRW: 900000,
    days: [
      {
        id: "day-1",
        date: "2025-10-24",
        label: "1일차 · 도착 & 도톤보리",
        spots: [
          {
            id: "s1",
            name: "간사이 국제공항",
            category: "교통",
            stayMinutes: 40,
            travelMinutes: 55,
            arrival: "11:00",
            hours: "24시간",
            memo: "하루카 특급 탑승",
          },
          {
            id: "s2",
            name: "호텔 체크인 (난바)",
            category: "숙소",
            stayMinutes: 30,
            travelMinutes: 12,
            arrival: "12:35",
            hours: "체크인 15:00 (짐만 맡김)",
            rating: 4.3,
          },
          {
            id: "s3",
            name: "이치란 라멘 도톤보리",
            category: "맛집",
            stayMinutes: 50,
            travelMinutes: 8,
            arrival: "13:20",
            hours: "24시간 · 대기 30분",
            rating: 4.1,
            memo: "돈코츠 + 반숙란",
          },
          {
            id: "s4",
            name: "도톤보리 글리코 사인",
            category: "관광지",
            stayMinutes: 60,
            travelMinutes: 10,
            arrival: "14:20",
            hours: "상시 개방",
            rating: 4.5,
          },
          {
            id: "s5",
            name: "호젠지 요코초",
            category: "관광지",
            stayMinutes: 45,
            travelMinutes: 0,
            arrival: "15:40",
            hours: "상시 개방",
            rating: 4.4,
          },
        ],
      },
      {
        id: "day-2",
        date: "2025-10-25",
        label: "2일차 · 교토 당일치기",
        spots: [
          {
            id: "s6",
            name: "후시미 이나리 신사",
            category: "관광지",
            stayMinutes: 120,
            travelMinutes: 35,
            arrival: "09:30",
            hours: "24시간",
            rating: 4.7,
            memo: "센본토리이 정상까지",
          },
          {
            id: "s7",
            name: "니시키 시장",
            category: "맛집",
            stayMinutes: 90,
            travelMinutes: 20,
            arrival: "12:25",
            hours: "10:00 - 18:00",
            rating: 4.2,
          },
          {
            id: "s8",
            name: "기요미즈데라",
            category: "관광지",
            stayMinutes: 100,
            travelMinutes: 40,
            arrival: "14:05",
            hours: "06:00 - 18:00",
            rating: 4.6,
          },
        ],
      },
      {
        id: "day-3",
        date: "2025-10-26",
        label: "3일차 · 유니버설 스튜디오",
        spots: [
          {
            id: "s9",
            name: "유니버설 스튜디오 재팬",
            category: "관광지",
            stayMinutes: 480,
            travelMinutes: 30,
            arrival: "09:00",
            hours: "08:30 - 21:00",
            rating: 4.6,
            memo: "익스프레스 패스 예약 완료",
          },
          {
            id: "s10",
            name: "우메다 스카이빌딩 야경",
            category: "관광지",
            stayMinutes: 70,
            travelMinutes: 0,
            arrival: "19:30",
            hours: "09:30 - 22:30",
            rating: 4.5,
          },
        ],
      },
    ],
    expenses: [
      { id: "e1", date: "2025-10-24", category: "교통", title: "하루카 특급 왕복", amount: 4380, currency: "JPY", amountKRW: 39858 },
      { id: "e2", date: "2025-10-24", category: "식비", title: "이치란 라멘", amount: 1980, currency: "JPY", amountKRW: 18018 },
      { id: "e3", date: "2025-10-24", category: "숙박", title: "난바 호텔 1박", amount: 12500, currency: "JPY", amountKRW: 113750 },
      { id: "e4", date: "2025-10-24", category: "식비", title: "타코야키 & 편의점", amount: 2200, currency: "JPY", amountKRW: 20020 },
      { id: "e5", date: "2025-10-25", category: "교통", title: "교토 왕복 전철", amount: 1140, currency: "JPY", amountKRW: 10374 },
      { id: "e6", date: "2025-10-25", category: "식비", title: "니시키 시장 먹거리", amount: 3400, currency: "JPY", amountKRW: 30940 },
      { id: "e7", date: "2025-10-25", category: "관광", title: "기요미즈데라 입장료", amount: 800, currency: "JPY", amountKRW: 7280 },
      { id: "e8", date: "2025-10-25", category: "숙박", title: "난바 호텔 1박", amount: 12500, currency: "JPY", amountKRW: 113750 },
      { id: "e9", date: "2025-10-26", category: "관광", title: "유니버설 1일권", amount: 8600, currency: "JPY", amountKRW: 78260 },
      { id: "e10", date: "2025-10-26", category: "쇼핑", title: "USJ 굿즈", amount: 6200, currency: "JPY", amountKRW: 56420 },
      { id: "e11", date: "2025-10-26", category: "식비", title: "USJ 내부 식사", amount: 3800, currency: "JPY", amountKRW: 34580 },
    ],
  },
  {
    id: "trip-bangkok",
    title: "방콕 휴양 & 야시장",
    destination: "방콕",
    country: "태국",
    startDate: "2025-12-20",
    endDate: "2025-12-24",
    coverColor: "var(--chart-2)",
    budgetKRW: 1100000,
    days: [
      {
        id: "bkk-day-1",
        date: "2025-12-20",
        label: "1일차 · 도착 & 카오산로드",
        spots: [
          {
            id: "b1",
            name: "수완나품 국제공항",
            category: "교통",
            stayMinutes: 40,
            travelMinutes: 50,
            arrival: "13:00",
            hours: "24시간",
          },
          {
            id: "b2",
            name: "카오산로드 야시장",
            category: "관광지",
            stayMinutes: 120,
            travelMinutes: 0,
            arrival: "19:00",
            hours: "16:00 - 02:00",
            rating: 4.2,
          },
        ],
      },
    ],
    expenses: [
      { id: "be1", date: "2025-12-20", category: "숙박", title: "수쿰빗 호텔 1박", amount: 2400, currency: "THB", amountKRW: 93600 },
      { id: "be2", date: "2025-12-20", category: "식비", title: "팟타이 & 망고밥", amount: 320, currency: "THB", amountKRW: 12480 },
      { id: "be3", date: "2025-12-20", category: "교통", title: "공항 택시", amount: 450, currency: "THB", amountKRW: 17550 },
    ],
  },
]
